/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type {
  Student,
  SubjectProgress,
  Interview,
  Survey,
  SurveyResponse,
} from "./types/types.ts";

export const INITIAL_STUDENTS: Student[] = [
  {
    id: "sofia_martinez",
    dni: "42.190.455",
    lastNames: "MARTÍNEZ",
    firstNames: "Sofía Valentina",
    fullName: "MARTÍNEZ, Sofía Valentina",
    email: "s.martinez@fi.mdp.edu.ar",
    avatarUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150",
    career: "Ingeniería en Informática",
    year: 3,
    legajo: "21.054/8",
    riskLevel: "CRÍTICO",
    riskValue: 9.2,
    tramo: "INICIAL",
    lastRecalculation: "14/10/2023 08:45",
    statusAlerta: "NUEVA",
    gpa: 6.42,
    subjectsApproved: 14,
    subjectsTotal: 36,
    engagement: "Bajo",
    phone: "+54 223 599-4422",
  },
  {
    id: "lucas_garcia",
    dni: "41.882.001",
    lastNames: "GARCÍA",
    firstNames: "Lucas Manuel",
    fullName: "GARCÍA, Lucas Manuel",
    email: "l.garcia@fi.mdp.edu.ar",
    avatarUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150",
    career: "Ingeniería Industrial",
    year: 2,
    legajo: "22.119/4",
    riskLevel: "MEDIO",
    riskValue: 5.4,
    tramo: "MEDIO",
    lastRecalculation: "14/10/2023 09:15",
    statusAlerta: "EN REVISIÓN",
    gpa: 7.15,
    subjectsApproved: 11,
    subjectsTotal: 34,
    engagement: "Medio",
    phone: "+54 223 488-9122",
  },
  {
    id: "ana_rodriguez",
    dni: "43.001.229",
    lastNames: "RODRÍGUEZ",
    firstNames: "Ana Lucía",
    fullName: "RODRÍGUEZ, Ana Lucía",
    email: "a.rodriguez@fi.mdp.edu.ar",
    avatarUrl:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150",
    career: "Ingeniería Industrial",
    year: 1,
    legajo: "23.401/1",
    riskLevel: "BAJO",
    riskValue: 1.2,
    tramo: "INICIAL",
    lastRecalculation: "13/10/2023 15:10",
    statusAlerta: "INTERVENIDA",
    gpa: 8.24,
    subjectsApproved: 4,
    subjectsTotal: 34,
    engagement: "Alto",
    phone: "+54 223 502-1134",
  },
  {
    id: "mateo_garcia",
    dni: "43.100.229",
    lastNames: "GARCÍA",
    firstNames: "Mateo",
    fullName: "GARCÍA, Mateo",
    email: "m.garcia@fi.mdp.edu.ar",
    avatarUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150",
    career: "Ingeniería Industrial",
    year: 3,
    legajo: "21.490/2",
    riskLevel: "SEGURO",
    riskValue: 0.8,
    tramo: "MEDIO",
    lastRecalculation: "14/10/2023 11:20",
    statusAlerta: "SIN ALERTA",
    gpa: 8.42,
    subjectsApproved: 18,
    subjectsTotal: 32,
    engagement: "Alto",
    phone: "+54 223 609-8877",
  },
  {
    id: "mateo_alvarado",
    dni: "42.990.111",
    lastNames: "ALVARADO",
    firstNames: "Mateo",
    fullName: "ALVARADO, Mateo",
    email: "m.alvarado@fi.mdp.edu.ar",
    avatarUrl:
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=150",
    career: "Ingeniería Industrial",
    year: 3,
    legajo: "21.059/1",
    riskLevel: "CRÍTICO",
    riskValue: 9.5,
    tramo: "INICIAL",
    lastRecalculation: "14/10/2023 09:12",
    statusAlerta: "NUEVA",
    gpa: 5.8,
    subjectsApproved: 10,
    subjectsTotal: 34,
    engagement: "Bajo",
    phone: "+54 223 411-9900",
  },
];

export const INITIAL_INTERVIEWS: Interview[] = [
  {
    id: "int_1",
    studentId: "sofia_martinez",
    studentName: "MARTÍNEZ, Sofía Elena",
    date: "24 MAY",
    time: "14:30 hs",
    modality: "Presencial",
    location: "Gabinete Psicopedagógico",
    status: "PENDIENTE",
  },
  {
    id: "int_2",
    studentId: "diego_sanchez",
    studentName: "SÁNCHEZ, Diego",
    date: "26 MAY",
    time: "09:00 hs",
    modality: "Presencial",
    location: "Aula 402",
    status: "PENDIENTE",
  },
];

export const MOCK_SURVEY_RESPONSES: SurveyResponse[] = [
  {
    id: "resp_1",
    studentName: "MARTÍNEZ, Sofía Valentina",
    submittedAt: "20/03/2024 10:15",
    answers: [
      { questionId: "q_1", answer: "Ingeniería en Informática" },
      { questionId: "q_2", answer: "Mejorar la empleabilidad" },
      { questionId: "q_3", answer: "Presencial" },
      { questionId: "q_4", answer: "4" },
      { questionId: "q_5", answer: "Sí" },
    ],
  },
  {
    id: "resp_2",
    studentName: "GARCÍA, Lucas Manuel",
    submittedAt: "20/03/2024 11:30",
    answers: [
      { questionId: "q_1", answer: "Ingeniería Industrial" },
      { questionId: "q_2", answer: "Interés en la industria" },
      { questionId: "q_3", answer: "Híbrida" },
      { questionId: "q_4", answer: "3" },
      { questionId: "q_5", answer: "Sí" },
    ],
  },
  {
    id: "resp_3",
    studentName: "RODRÍGUEZ, Ana Lucía",
    submittedAt: "21/03/2024 09:45",
    answers: [
      { questionId: "q_1", answer: "Ingeniería Industrial" },
      { questionId: "q_2", answer: "Vinculación con el sector productivo" },
      { questionId: "q_3", answer: "Presencial" },
      { questionId: "q_4", answer: "5" },
      { questionId: "q_5", answer: "Sí" },
    ],
  },
  {
    id: "resp_4",
    studentName: "GARCÍA, Mateo",
    submittedAt: "21/03/2024 14:20",
    answers: [
      { questionId: "q_1", answer: "Ingeniería Industrial" },
      { questionId: "q_2", answer: "Salida laboral" },
      { questionId: "q_3", answer: "Presencial" },
      { questionId: "q_4", answer: "4" },
      { questionId: "q_5", answer: "No" },
    ],
  },
  {
    id: "resp_5",
    studentName: "ALVARADO, Mateo",
    submittedAt: "22/03/2024 08:10",
    answers: [
      { questionId: "q_1", answer: "Ingeniería Industrial" },
      { questionId: "q_2", answer: "Tradición familiar" },
      { questionId: "q_3", answer: "Virtual" },
      { questionId: "q_4", answer: "2" },
      { questionId: "q_5", answer: "No" },
    ],
  },
];

export const INITIAL_SURVEYS: Survey[] = [
  {
    id: "sur_1",
    title: "Encuesta de Ingreso 2024",
    description: "Ciclo Lectivo 2024 - Ingeniería",
    type: "Única",
    status: "Activa",
    creationDate: "15/02/2024",
    responsesCount: 412,
    responseRate: 68.4,
    urgentCasesCount: 14,
    questions: [
      {
        id: "q_1",
        texto: "¿Qué carrera elegiste?",
        tipo: "texto_libre",
        obligatoria: true,
      },
      {
        id: "q_2",
        texto: "¿Cuál fue tu principal motivación para elegir esta carrera?",
        tipo: "texto_libre",
        obligatoria: true,
      },
      {
        id: "q_3",
        texto: "¿Qué modalidad de cursada preferís?",
        tipo: "opcion_multiple",
        opciones: ["Presencial", "Virtual", "Híbrida"],
        obligatoria: true,
      },
      {
        id: "q_4",
        texto: "Del 1 al 5, ¿cómo calificás tu experiencia en el ingreso?",
        tipo: "escala",
        obligatoria: true,
      },
      {
        id: "q_5",
        texto: "¿Contás con computadora personal para estudiar?",
        tipo: "si_no",
        obligatoria: true,
      },
    ],
    responses: MOCK_SURVEY_RESPONSES,
  },
  {
    id: "sur_2",
    title: "Satisfacción Cuatrimestral Q1",
    description: "Evaluación de cursada - Periodo 1",
    type: "Periódica",
    status: "Borrador",
    creationDate: "03/03/2024",
    responsesCount: 0,
    responseRate: 0,
    urgentCasesCount: 0,
  },
  {
    id: "sur_3",
    title: "Encuesta de Deserción Tardía",
    description: "Alumnos > 50% de carrera",
    type: "Única",
    status: "Finalizada",
    creationDate: "10/01/2024",
    responsesCount: 189,
    responseRate: 92.0,
    urgentCasesCount: 3,
  },
];

export const SUBJECTS_SOFIA: SubjectProgress[] = [
  {
    code: "MAT2",
    name: "Análisis Matemático II",
    teacher: "Ing. Rodríguez",
    midtermGrades: "2, 4 (Recuperatorio)",
    finalGrade: "-",
    assistance: 55,
    status: "EN RIESGO",
  },
  {
    code: "AED1",
    name: "Algorítmos y Estructuras I",
    teacher: "Lic. Mastronardi",
    midtermGrades: "7, 6",
    finalGrade: "8",
    assistance: 92,
    status: "APROBADA",
  },
  {
    code: "ADC",
    name: "Arquitectura de Computadoras",
    teacher: "Lic. Mastronardi",
    midtermGrades: "5, 3",
    finalGrade: "-",
    assistance: 80,
    status: "CURSANDO",
  },
  {
    code: "ENG2",
    name: "Inglés Técnico II",
    teacher: "Dra. Valenti",
    midtermGrades: "9, 8",
    finalGrade: "9",
    assistance: 95,
    status: "PROMOCIONADA",
  },
];

export const SUBJECTS_MATEO: SubjectProgress[] = [
  {
    code: "MAT2",
    name: "Análisis Matemático II",
    teacher: "Ing. Rodríguez",
    midtermGrades: "8, 7",
    finalGrade: "7.5",
    assistance: 89,
    status: "APROBADA",
  },
  {
    code: "FIS2",
    name: "Física II",
    teacher: "Lic. Mastronardi",
    midtermGrades: "7, 9",
    finalGrade: "8.0",
    assistance: 90,
    status: "APROBADA",
  },
  {
    code: "POO",
    name: "Programación Orientada a Objetos",
    teacher: "Ing. Soria",
    midtermGrades: "9, 10",
    finalGrade: "9.5",
    assistance: 96,
    status: "APROBADA",
  },
  {
    code: "EST1",
    name: "Estadística I",
    teacher: "Dra. Valenti",
    midtermGrades: "Cursando",
    finalGrade: "-",
    assistance: 85,
    status: "CURSANDO",
  },
];
